services:
  offerworker:
    image: offerworker
    deploy:
      replicas: 1
    build:
      context: .
      dockerfile: OfferWorker/Dockerfile
    environment:
      - MSSQL_SA_PASSWORD=Password1*
    restart: on-failure
    depends_on:
      - rabbitmq
    
  openlane:
    image: openlane
    deploy:
      replicas: 1
    build:
      context: .
      dockerfile: Openlane/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    ports:
      - "5000:8080"
      
  rabbitmq:
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password1*
    ports:
      - "1433:1433"