services:
  offerworker:
    image: offerworker
    deploy:
      replicas: 1
    build:
      context: .
      dockerfile: OfferWorker/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    
  openlane:
    image: openlane
    deploy:
      replicas: 1
    build:
      context: .
      dockerfile: Openlane/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    ports:
      - "5000:5000"
      - "5001:5001"
      
  rabbitmq:
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
