services:
  worker-base:
    image: offerworker
    build:
      context: .
      dockerfile: OfferWorker/Dockerfile
    environment:
      - MSSQL_SA_PASSWORD=Password1*
      - EnsureCreated=true
    restart: on-failure
    depends_on:
      - rabbitmq
  
  # This way, the scaled workers won't try EnsureCreated()
  worker-extra:
    image: offerworker
    deploy:
      replicas: 3
    build:
      context: .
      dockerfile: OfferWorker/Dockerfile
    environment:
      - MSSQL_SA_PASSWORD=Password1*
    restart: on-failure
    depends_on:
      - rabbitmq
      - worker-base
  
  api:
    image: api
    build:
      context: .
      dockerfile: API/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    ports:
      - "5000:8080"
      
  rabbitmq:
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password1*
    ports:
      - "1433:1433"