services:
  event-processor-base:
    image: eventprocessor
    build:
      context: .
      dockerfile: EventProcessor/Dockerfile
    environment:
      - MSSQL_SA_PASSWORD=Password1*
      - EnsureCreated=true
      - EnsureDeleted=false
      - SeedDb=true
    depends_on:
      - rabbitmq
  
  # This way, the scaled workers won't try EnsureCreated()
  event-processor-extra:
    image: eventprocessor
    deploy:
      replicas: 1
    build:
      context: .
      dockerfile: EventProcessor/Dockerfile
    environment:
      - MSSQL_SA_PASSWORD=Password1*
    depends_on:
      - rabbitmq
      - event-processor-base
  
  api:
    image: api
    build:
      context: .
      dockerfile: API/Dockerfile
    environment:
      - MSSQL_SA_PASSWORD=Password1*
    restart: on-failure
    depends_on:
      - rabbitmq
    ports:
      - "5000:8080"
      
  rabbitmq:
    image: masstransit/rabbitmq
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password1*
    ports:
      - "1433:1433"